### ISSUE TITLE
Sanity Check Failure

### ISSUE THREAD

**Issue by jaypantone** [PermutaTriangle/Tilings#123]
```python
basis = "1324"
pack = TileScopePack.row_and_col_placements(partial=False)
css = TileScope(basis, pack, debug=True)
spec = css.auto_search(status_update=30)
```
produces, after a few seconds, the error
```python
[D 200514 17:41:49 comb_spec_searcher:225] Adding combinatorial rule 22 -> (1, 73, 74, 75)
    Explanation: placing the rightmost point in column 0
    +-+                                      +-+     +-+-+                                    +-+-+                                    +-+-+
    |3|                                   =  | |  +  |3| |                                 +  |3| |                                 +  |2| |
    +-+                                      +-+     +-+-+                                    +-+-+                                    +-+-+
    |2|                                              |2| |                                    |2| |                                    | |●|
    +-+                                              +-+-+                                    +-+-+                                    +-+-+
    |1|                                              | |●|                                    |1| |                                    |/| |
    +-+                                              +-+-+                                    +-+-+                                    +-+-+
    1: Av(021)                                       |1| |                                    | |●|                                    |1| |
    2: Av(0213)                                      +-+-+                                    +-+-+                                    +-+-+
    3: Av(102)                                       |1| |                                    |1| |                                    |1| |
    Crossing obstructions:                           +-+-+                                    +-+-+                                    +-+-+
    0213: (0, 0), (0, 1), (0, 0), (0, 1)             1: Av(021)                               1: Av(021)                               /: Av(10)
    0213: (0, 0), (0, 1), (0, 0), (0, 2)             2: Av(0213)                              2: Av(0213)                              1: Av(021)
    0213: (0, 0), (0, 1), (0, 1), (0, 1)             3: Av(102)                               3: Av(102)                               2: Av(102)
    0213: (0, 0), (0, 1), (0, 1), (0, 2)             ●: point                                 ●: point                                 ●: point
    0213: (0, 0), (0, 2), (0, 0), (0, 2)             Crossing obstructions:                   Crossing obstructions:                   Crossing obstructions:
    0213: (0, 0), (0, 2), (0, 1), (0, 2)             021: (0, 0), (0, 1), (0, 0)              01: (0, 0), (0, 2)                       021: (0, 0), (0, 1), (0, 0)
    0213: (0, 1), (0, 1), (0, 1), (0, 2)             021: (0, 0), (0, 1), (0, 1)              0213: (0, 0), (0, 3), (0, 0), (0, 3)     021: (0, 0), (0, 1), (0, 1)
    0213: (0, 1), (0, 2), (0, 1), (0, 2)             0213: (0, 0), (0, 3), (0, 0), (0, 3)     0213: (0, 0), (0, 3), (0, 0), (0, 4)     021: (0, 0), (0, 2), (0, 0)
                                                     0213: (0, 0), (0, 3), (0, 0), (0, 4)     0213: (0, 0), (0, 3), (0, 3), (0, 3)     021: (0, 0), (0, 2), (0, 1)
                                                     0213: (0, 0), (0, 3), (0, 1), (0, 3)     0213: (0, 0), (0, 3), (0, 3), (0, 4)     021: (0, 1), (0, 2), (0, 1)
                                                     0213: (0, 0), (0, 3), (0, 1), (0, 4)     0213: (0, 0), (0, 4), (0, 0), (0, 4)     102: (0, 4), (0, 2), (0, 4)
                                                     0213: (0, 0), (0, 3), (0, 3), (0, 3)     0213: (0, 0), (0, 4), (0, 3), (0, 4)     0213: (0, 0), (0, 4), (0, 0), (0, 4)
                                                     0213: (0, 0), (0, 3), (0, 3), (0, 4)     0213: (0, 2), (0, 3), (0, 2), (0, 3)     0213: (0, 0), (0, 4), (0, 1), (0, 4)
                                                     0213: (0, 0), (0, 4), (0, 0), (0, 4)     0213: (0, 2), (0, 3), (0, 2), (0, 4)     0213: (0, 1), (0, 4), (0, 1), (0, 4)
                                                     0213: (0, 0), (0, 4), (0, 1), (0, 4)     0213: (0, 2), (0, 3), (0, 3), (0, 3)     Requirement 0:
                                                     0213: (0, 0), (0, 4), (0, 3), (0, 4)     0213: (0, 2), (0, 3), (0, 3), (0, 4)     0: (1, 3)
                                                     0213: (0, 1), (0, 3), (0, 1), (0, 3)     0213: (0, 2), (0, 4), (0, 2), (0, 4)
                                                     0213: (0, 1), (0, 3), (0, 1), (0, 4)     0213: (0, 2), (0, 4), (0, 3), (0, 4)
                                                     0213: (0, 1), (0, 3), (0, 3), (0, 3)     0213: (0, 3), (0, 3), (0, 3), (0, 4)
                                                     0213: (0, 1), (0, 3), (0, 3), (0, 4)     0213: (0, 3), (0, 4), (0, 3), (0, 4)
                                                     0213: (0, 1), (0, 4), (0, 1), (0, 4)     Requirement 0:
                                                     0213: (0, 1), (0, 4), (0, 3), (0, 4)     0: (1, 1)
                                                     0213: (0, 3), (0, 3), (0, 3), (0, 4)
                                                     0213: (0, 3), (0, 4), (0, 3), (0, 4)
                                                     Requirement 0:
                                                     0: (1, 2)
Traceback (most recent call last):
  File "/Users/jay/Dropbox/Research/Active/2017-44-ATRAP/repos/comb_spec_searcher/comb_spec_searcher/strategies/rule.py", line 219, in sanity_check
    assert actual_objects == rule_objects
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_tilescope.py", line 54, in <module>
    spec = css.auto_search(status_update=30)
  File "/Users/jay/Dropbox/Research/Active/2017-44-ATRAP/repos/comb_spec_searcher/comb_spec_searcher/comb_spec_searcher.py", line 551, in auto_search
    self._expand(label, strategies, inferral)
  File "/Users/jay/Dropbox/Research/Active/2017-44-ATRAP/repos/comb_spec_searcher/comb_spec_searcher/comb_spec_searcher.py", line 153, in _expand
    comb_class, strategy_generator, label
  File "/Users/jay/Dropbox/Research/Active/2017-44-ATRAP/repos/comb_spec_searcher/comb_spec_searcher/utils.py", line 49, in inner
    for res in func(css, *args, **kwargs):
  File "/Users/jay/Dropbox/Research/Active/2017-44-ATRAP/repos/comb_spec_searcher/comb_spec_searcher/comb_spec_searcher.py", line 231, in _expand_class_with_strategy
    rule.sanity_check(n=i)
  File "/Users/jay/Dropbox/Research/Active/2017-44-ATRAP/repos/comb_spec_searcher/comb_spec_searcher/strategies/rule.py", line 227, in sanity_check
    + ["{} = {}".format(p, v) for p, v in parameters]
comb_spec_searcher.exception.SanityCheckFailure: The following rule failed sanity check:
Explanation: placing the rightmost point in column 0
```

**Comment by jaypantone** [comment]
Okay, never mind. I pulled on Tilings and it's fine. I guess I randomly discovered a bug just after it was fixed?

**Comment by christianbean** [comment]
You refound a bug you told me about two days ago!
