### ISSUE TITLE
Fusion bug after long run

### ISSUE THREAD

**Issue by jaypantone** [PermutaTriangle/Tilings#180]
After some long amount of time (6-8 hours?) of running `0123_0231` with `point_placements` and the single fusion RuleDB, the following error occurs:

```python
error with class:  0123_0231
0123_0231
point_placements_fusion_single_fusion_mark_verified
Looking for recursive combinatorial specification with the strategies:
Inferral: row and column separation, obstruction transitivity
Initial: add assumptions, splitting the assumptions, requirement placement, tracked fusion
Verification: verify atoms, insertion encoding verified, one by one verification, locally factorable verification
Set 1: unions of factor, point insertion
Set 2: requirement corroboration

Traceback (most recent call last):
  File "/users/personnel/jay/atrap/repos/Tilings/tilings/tiling.py", line 1128, in get_parameter
    idx = self._assumptions.index(assumption)
ValueError: tuple.index(x): x not in tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/personnel/jay/atrap/repos/handy-scripts/jay/hammer/hammer.py", line 86, in run_work_packet
    spec = css.auto_search(perc=10)
  File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/comb_spec_searcher.py", line 596, in auto_search
    self._expand(comb_class, label, strategies, inferral)
  File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/comb_spec_searcher.py", line 176, in _expand
    self._add_rule(start_label, end_labels, rule)
  File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/comb_spec_searcher.py", line 321, in _add_rule
    self.ruledb.add(start_label, tuple(cleaned_end_labels), rule)
  File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/rule_db/base.py", line 61, in add
    and rule.constructor.is_equivalence()
  File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/strategies/rule.py", line 317, in constructor
    self.comb_class, self.children
  File "/users/personnel/jay/atrap/repos/Tilings/tilings/strategies/fusion.py", line 513, in constructor
    self.extra_parameters(comb_class, children)[0],
  File "/users/personnel/jay/atrap/repos/Tilings/tilings/strategies/fusion.py", line 533, in extra_parameters
    for k, ass in zip(comb_class.extra_parameters, mapped_assumptions)
  File "/users/personnel/jay/atrap/repos/Tilings/tilings/strategies/fusion.py", line 533, in <dictcomp>
    for k, ass in zip(comb_class.extra_parameters, mapped_assumptions)
  File "/users/personnel/jay/atrap/repos/Tilings/tilings/tiling.py", line 1130, in get_parameter
    raise ValueError(f"following assumption not on tiling: '{assumption}'")
ValueError: following assumption not on tiling: 'can count occurrences of
0: (0, 0)'
```

I will provide a script shortly that I *think* should recreate it, but if it does it will take many hours.

**Comment by jaypantone** [comment]
I think this should recreate it
```python
from tilings.strategies.fusion import FusionStrategy
from tilings.tilescope import TileScope, TileScopePack
from comb_spec_searcher.rule_db import LimitedStrategyRuleDB


basis = "0123_0231"
pack = TileScopePack.point_placements().make_fusion(tracked=True)
ruledb = LimitedStrategyRuleDB(set([FusionStrategy]), 1, True)
css = TileScope(basis, pack, ruledb=ruledb)
spec = css.auto_search(perc=10)
```

**Comment by jaypantone** [comment]
I have been running on the new branch for 12 hours and this has not reappeared yet. But also, it appears to be a bug that we later fixed anyway. If you agree @christianbean, feel free to close this.
