### ISSUE TITLE
AssertionError: insert 0 in cell (2, 2)

### ISSUE THREAD

**Issue by jaypantone** [PermutaTriangle/Tilings#189]
Replicates in 30ish minutes with
```python
from tilings.tilescope import TileScope, TileScopePack

basis = '0123_0231'
pack = TileScopePack.insertion_point_placements().make_fusion(apply_first=True)
css = TileScope(basis, pack)
spec = css.auto_search()
```

Full traceback
```python
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-1-99790a70f273> in <module>
      4 pack = TileScopePack.insertion_point_placements().make_fusion(apply_first=True)
      5 css = TileScope(basis, pack)
----> 6 spec = css.auto_search()

~/Dropbox/Research/Active/2017-44-ATRAP/repos/comb_spec_searcher/comb_spec_searcher/comb_spec_searcher.py in auto_search(self, **kwargs)
    594                     last_label = label
    595                 if not self.ruledb.is_verified(label):
--> 596                     self._expand(comb_class, label, strategies, inferral)
    597                 if time.time() - expansion_start > max_expansion_time:
    598                     break

~/Dropbox/Research/Active/2017-44-ATRAP/repos/comb_spec_searcher/comb_spec_searcher/comb_spec_searcher.py in _expand(self, comb_class, label, strategies, inferral)
    174                     comb_class, strategy_generator, label
    175                 ):
--> 176                     self._add_rule(start_label, end_labels, rule)
    177
    178     def _rules_from_strategy(

~/Dropbox/Research/Active/2017-44-ATRAP/repos/comb_spec_searcher/comb_spec_searcher/comb_spec_searcher.py in _add_rule(self, start_label, end_labels, rule)
    318         if not cleaned_end_labels:
    319             # this must be a verification strategy!
--> 320             assert isinstance(rule, VerificationRule), rule.formal_step
    321         self.ruledb.add(start_label, tuple(cleaned_end_labels), rule)
    322

AssertionError: insert 0 in cell (2, 2)
```

**Comment by jaypantone** [comment]
This has appeared for 5 classes with some kind of `insert in cell ...` message. It's now popped up with a different strategy (I think this is related...)

```python
error with class:  0123_0132_0213
0123_0132_0213
insertion_row_and_col_placements_fusion
Looking for recursive combinatorial specification with the strategies:
Inferral: row and column separation, obstruction transitivity
Initial: tracked fusion, add assumptions, splitting the assumptions, factor, requirement corroboration, point insertion
Verification: verify atoms, insertion encoding verified, one by one verification, locally factorable verification
Set 1: row and column placement

Traceback (most recent call last):
  File "/users/personnel/jay/atrap/repos/handy-scripts/jay/surveyor/surveyor.py", line 104, in run_work_packet
    spec = css.auto_search(max_time=time_to_try)
  File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/comb_spec_searcher.py", line 596, in auto_search
    self._expand(comb_class, label, strategies, inferral)
  File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/comb_spec_searcher.py", line 176, in _expand
    self._add_rule(start_label, end_labels, rule)
  File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/comb_spec_searcher.py", line 320, in _add_rule
    assert isinstance(rule, VerificationRule), rule.formal_step
AssertionError: splitting the assumptions
```

**Comment by christianbean** [comment]
I think this could have been related to the forget db issue.

**Comment by christianbean** [comment]
After some hunting, I found the two offending rules from the above comments:
```
insert 0 in cell (2, 2)
+-+-+-+-+-+                                  +-+-+-+-+                                    +-+-+-+-+                           
|1|\|\| |2|                               =  |1|\| |●|                                 +  |1|\|\|2|                           
+-+-+-+-+-+                                  +-+-+-+-+                                    +-+-+-+-+                           
| | | | |2|                                  | | | |●|                                    1: Av(012)                          
+-+-+-+-+-+                                  +-+-+-+-+                                    2: Av+(10, 012)                     
| | | |\| |                                  | | |\| |                                    \: Av(01)                           
+-+-+-+-+-+                                  +-+-+-+-+                                    \: Av+(01)                          
1: Av(012)                                   1: Av(012)                                   Crossing obstructions:              
2: Av(10, 012)                               \: Av(01)                                    01: (1, 0), (2, 0)                  
\: Av(01)                                    \: Av+(01)                                   10: (1, 0), (3, 0)                  
Crossing obstructions:                       ●: point                                     10: (2, 0), (3, 0)                  
01: (1, 2), (2, 2)                           Crossing obstructions:                       012: (0, 0), (0, 0), (1, 0)         
10: (1, 2), (4, 2)                           01: (3, 1), (3, 2)                           012: (0, 0), (0, 0), (2, 0)         
10: (2, 2), (4, 1)                           10: (1, 2), (3, 2)                           012: (1, 0), (3, 0), (3, 0)         
10: (2, 2), (4, 2)                           012: (0, 2), (0, 2), (1, 2)                  012: (2, 0), (3, 0), (3, 0)         
012: (0, 2), (0, 2), (1, 2)                  021: (0, 2), (0, 2), (3, 2)                  021: (0, 0), (0, 0), (3, 0)         
012: (0, 2), (0, 2), (2, 2)                  Requirement 0:                               0123: (0, 0), (0, 0), (3, 0), (3, 0)
012: (1, 2), (4, 2), (4, 2)                  0: (2, 0)                                    Requirement 0:                      
012: (2, 2), (4, 2), (4, 2)                  Requirement 1:                               0: (2, 0)                           
012: (3, 0), (4, 1), (4, 1)                  10: (3, 1), (3, 2)                           Requirement 1:                      
012: (3, 0), (4, 1), (4, 2)                  Assumption 0:                                01: (3, 0), (3, 0)                  
012: (3, 0), (4, 2), (4, 2)                  can count points in cells (3, 1), (3, 2)     Assumption 0:                       
012: (4, 1), (4, 1), (4, 2)                                                               can count points in cell (3, 0)     
012: (4, 1), (4, 2), (4, 2)                                                               
021: (0, 2), (0, 2), (4, 2)                                                               
120: (4, 2), (4, 2), (4, 1)                                                               
0123: (0, 2), (0, 2), (4, 2), (4, 2)                                                      
Requirement 0:                                                                            
0: (2, 2)                                                                                 
0: (3, 0)                                                                                 
Requirement 1:                                                                            
01: (4, 1), (4, 1)                                                                        
01: (4, 1), (4, 2)                                                                        
01: (4, 2), (4, 2)                                                                        
10: (4, 1), (4, 2)                                                                        
Assumption 0:                                                                             
can count points in cells (4, 1), (4, 2)
 ```
and 
```
splitting the assumptions
+-+-+-+-+                                                    +-+-+-+-+                               
|1| |2| |                                                 ↣  |1| |2| |                               
+-+-+-+-+                                                    +-+-+-+-+                               
| |●| | |                                                    | |●| | |                               
+-+-+-+-+                                                    +-+-+-+-+                               
|○| | | |                                                    |○| | | |                               
+-+-+-+-+                                                    +-+-+-+-+                               
| | | |○|                                                    | | | |○|                               
+-+-+-+-+                                                    +-+-+-+-+                               
|\| | | |                                                    |\| | | |                               
+-+-+-+-+                                                    +-+-+-+-+                               
1: Av(012, 021, 102)                                         1: Av(012, 021, 102)                    
2: Av+()                                                     2: Av+()                                
\: Av+(01)                                                   \: Av+(01)                              
○: Av(01, 10)                                                ○: Av(01, 10)                           
●: point                                                     ●: point                                
Crossing obstructions:                                       Crossing obstructions:                  
01: (0, 2), (0, 4)                                           01: (0, 2), (0, 4)                      
Requirement 0:                                               Requirement 0:                          
0: (0, 0)                                                    0: (0, 0)                               
Requirement 1:                                               Requirement 1:                          
0: (1, 3)                                                    0: (1, 3)                               
Requirement 2:                                               Requirement 2:                          
10: (2, 4), (0, 2)                                           10: (2, 4), (0, 2)                      
10: (2, 4), (0, 4)                                           10: (2, 4), (0, 4)                      
Assumption 0:                                                Assumption 0:                           
can count points in cells (0, 2), (0, 4), (1, 3), (3, 1)     can count points in cells (0, 2), (0, 4)
                                                             Assumption 1:                           
                                                             can count points in cell (1, 3)         
                                                             Assumption 2:                           
                                                             can count points in cell (3, 1)  
```
Both parent tilings are bizarre! The first more so (it contains an Av+()). I think the real issue is that the requirement gridded perms are contradictory, so the parent tilings should never have exisited in the universe. 

I assume I am getting these requirements wrong when I insert the 12 and 21 requirements. When rows/columns with more than one cell merge I had to consider all possible 12/21 gridded perms crossing in the fused row or column, I must have got this wrong. Will continue to investigate.
