### ISSUE TITLE
NoMoreClassesToExpandError

### ISSUE THREAD

**Issue by jaypantone** [PermutaTriangle/Tilings#190]
This should replicate (not sure how long it takes, will update later)
```python
from tilings.tilescope import TileScope, TileScopePack
from comb_spec_searcher.rule_db import LimitedStrategyRuleDB
from tilings.strategies.fusion import FusionStrategy

basis = '0123_1230'
pack = TileScopePack.insertion_row_and_col_placements(row_only=True).make_fusion(apply_first=True)
css = TileScope(basis, pack)
spec = css.auto_search()
```

Full traceback:
```
[E 200625 19:12:30 surveyor:211] 0123_1230
    insertion_row_placements_fusion
    Looking for recursive combinatorial specification with the strategies:
    Inferral: row and column separation, obstruction transitivity
    Initial: tracked fusion, add assumptions, splitting the assumptions, factor, requirement corroboration, point insertion
    Verification: verify atoms, insertion encoding verified, one by one verification, locally factorable verification
    Set 1: row placement

    Traceback (most recent call last):
      File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/class_queue.py", line 228, in do_level
        yield next(self)
      File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/class_queue.py", line 217, in __next__
        self._populate_staging()
      File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/class_queue.py", line 169, in _populate_staging
        self._change_level()
      File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/class_queue.py", line 182, in _change_level
        raise StopIteration
    StopIteration

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/specification.py", line 159, in _expand_verified_comb_classes
        css.do_level()
      File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/comb_spec_searcher.py", line 406, in do_level
        for label, strategies, inferral in self.classqueue.do_level():
      File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/class_queue.py", line 231, in do_level
        raise NoMoreClassesToExpandError
    comb_spec_searcher.exception.NoMoreClassesToExpandError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/users/personnel/jay/atrap/repos/handy-scripts/jay/surveyor/surveyor.py", line 104, in run_work_packet
        spec = css.auto_search(max_time=time_to_try)
      File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/comb_spec_searcher.py", line 613, in auto_search
        minimization_time_limit=0.01 * (time.time() - auto_search_start),
      File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/utils.py", line 30, in inner
        res = func(css, *args, **kwargs)
      File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/comb_spec_searcher.py", line 676, in get_specification
        expand_verified=expand_verified,
      File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/specification.py", line 75, in __init__
        self._populate_rules_dict(strategies, equivalence_paths, expand_verified)
      File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/specification.py", line 123, in _populate_rules_dict
        self._expand_verified_comb_classes(verification_packs)
      File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/specification.py", line 163, in _expand_verified_comb_classes
        css.start_label
      File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/rule_db/base.py", line 256, in get_smallest_specification
        raise SpecificationNotFound("No specification for label {}".format(label))
    comb_spec_searcher.exception.SpecificationNotFound: No specification for label 0
```

**Comment by jaypantone** [comment]
After several tries, I finally recreated, and the problem is with computing the specifications for the verified nodes. See below.

```python
Python 3.6.9 (?, Apr 18 2020, 00:54:59)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.14.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %paste
from tilings.tilescope import TileScope, TileScopePack
from comb_spec_searcher.rule_db import LimitedStrategyRuleDB
from tilings.strategies.fusion import FusionStrategy

basis = '0123_1230'
pack = TileScopePack.insertion_row_and_col_placements(row_only=True).make_fusion(apply_first=True)
css = TileScope(basis, pack)
spec = css.auto_search()

## -- End pasted text --
[I 200625 21:17:41 comb_spec_searcher:584] Auto search started Fri, 26 Jun 2020 02:17:41
    Initialising CombSpecSearcher for the combinatorial class:
    +-+
    |1|
    +-+
    1: Av(0123, 1230)

    Looking for recursive combinatorial specification with the strategies:
    Inferral: row and column separation, obstruction transitivity
    Initial: tracked fusion, add assumptions, splitting the assumptions, factor, requirement corroboration, point insertion
    Verification: verify atoms, insertion encoding verified, one by one verification, locally factorable verification
    Set 1: row placement

[I 200625 21:28:20 comb_spec_searcher:670] Creating a specification
[I 200625 21:28:22 specification:157] Initialising CombSpecSearcher for the combinatorial class:
    +-+
    |\|
    +-+
    \: Av+(01)
    Requirement 0:
    0: (0, 0)
    Assumption 0:
    can count points in cell (0, 0)
    Looking for recursive combinatorial specification with the strategies:
    Inferral:
    Initial: splitting the assumptions, factor, requirement corroboration, point insertion
    Verification: already verified, verify atoms
    Set 1: column placement

[I 200625 21:28:22 specification:157] Initialising CombSpecSearcher for the combinatorial class:
    +-+
    |1|
    +-+
    1: Av+(012)
    Requirement 0:
    0: (0, 0)
    Assumption 0:
    can count points in cell (0, 0)
    Looking for recursive combinatorial specification with the strategies:
    Inferral: row and column separation, obstruction transitivity
    Initial: add assumptions, splitting the assumptions, factor, requirement corroboration, tracked fusion
    Verification: already verified, verify atoms, insertion encoding verified, one by one verification, locally factorable verification
    Set 1: row placement

[I 200625 21:28:23 specification:157] Initialising CombSpecSearcher for the combinatorial class:
    +-+-+-+
    |\|\|\|
    +-+-+-+
    \: Av+(01)
    Crossing obstructions:
    01: (0, 0), (1, 0)
    Requirement 0:
    0: (0, 0)
    Requirement 1:
    0: (1, 0)
    Requirement 2:
    0: (2, 0)
    Assumption 0:
    can count points in cell (0, 0)
    Assumption 1:
    can count points in cell (1, 0)
    Looking for recursive combinatorial specification with the strategies:
    Inferral:
    Initial: splitting the assumptions, factor, requirement corroboration, point insertion
    Verification: already verified, verify atoms
    Set 1: row placement

[I 200625 21:28:23 specification:157] Initialising CombSpecSearcher for the combinatorial class:
    +-+-+-+
    |\|\|\|
    +-+-+-+
    \: Av+(01)
    \: Av(01)
    Crossing obstructions:
    120: (0, 0), (1, 0), (2, 0)
    Requirement 0:
    10: (0, 0), (0, 0)
    Requirement 1:
    10: (1, 0), (1, 0)
    Assumption 0:
    can count points in cell (0, 0)
    Assumption 1:
    can count points in cell (1, 0)
    Looking for recursive combinatorial specification with the strategies:
    Inferral:
    Initial: splitting the assumptions, factor, requirement corroboration, point insertion
    Verification: already verified, verify atoms
    Set 1: row placement

[I 200625 21:28:23 specification:157] Initialising CombSpecSearcher for the combinatorial class:
    +-+-+-+-+
    |\|\|\|\|
    +-+-+-+-+
    \: Av+(01)
    \: Av(01)
    Crossing obstructions:
    01: (0, 0), (1, 0)
    10: (0, 0), (3, 0)
    10: (1, 0), (3, 0)
    Requirement 0:
    0: (0, 0)
    Requirement 1:
    0: (3, 0)
    Requirement 2:
    10: (2, 0), (2, 0)
    Assumption 0:
    can count points in cell (0, 0)
    Assumption 1:
    can count points in cell (2, 0)
    Looking for recursive combinatorial specification with the strategies:
    Inferral:
    Initial: splitting the assumptions, factor, requirement corroboration, point insertion
    Verification: already verified, verify atoms
    Set 1: row placement

[I 200625 21:28:23 specification:157] Initialising CombSpecSearcher for the combinatorial class:
    +-+-+-+
    |\|\|\|
    +-+-+-+
    \: Av+(01)
    Crossing obstructions:
    10: (0, 0), (2, 0)
    Requirement 0:
    0: (1, 0)
    Requirement 1:
    0: (2, 0)
    Requirement 2:
    10: (0, 0), (0, 0)
    Assumption 0:
    can count points in cell (0, 0)
    Assumption 1:
    can count points in cell (1, 0)
    Looking for recursive combinatorial specification with the strategies:
    Inferral:
    Initial: splitting the assumptions, factor, requirement corroboration, point insertion
    Verification: already verified, verify atoms
    Set 1: row placement

[I 200625 21:28:23 specification:157] Initialising CombSpecSearcher for the combinatorial class:
    +-+-+
    |\|\|
    +-+-+
    \: Av+(01)
    Requirement 0:
    0: (0, 0)
    Requirement 1:
    10: (1, 0), (1, 0)
    Assumption 0:
    can count points in cell (0, 0)
    Assumption 1:
    can count points in cells (0, 0), (1, 0)
    Assumption 2:
    can count points in cell (1, 0)
    Looking for recursive combinatorial specification with the strategies:
    Inferral:
    Initial: splitting the assumptions, factor, requirement corroboration, point insertion
    Verification: already verified, verify atoms
    Set 1: row placement

[I 200625 21:28:24 specification:157] Initialising CombSpecSearcher for the combinatorial class:
    +-+-+-+
    | |●| |
    +-+-+-+
    |\| |\|
    +-+-+-+
    \: Av+(01)
    ●: point
    Requirement 0:
    0: (1, 1)
    Requirement 1:
    0: (2, 0)
    Requirement 2:
    10: (0, 0), (0, 0)
    Assumption 0:
    can count points in cell (0, 0)
    Assumption 1:
    can count points in cells (0, 0), (2, 0)
    Assumption 2:
    can count points in cell (1, 1)
    Assumption 3:
    can count points in cell (2, 0)
    Looking for recursive combinatorial specification with the strategies:
    Inferral:
    Initial: splitting the assumptions, factor, requirement corroboration
    Verification: already verified, verify atoms, one by one verification, monotone tree verification, local verification
    Set 1: all factor insertion

---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
~/Dropbox/Research/Active/2017-44-ATRAP/repos/comb_spec_searcher/comb_spec_searcher/class_queue.py in do_level(self)
    227             try:
--> 228                 yield next(self)
    229             except StopIteration:

~/Dropbox/Research/Active/2017-44-ATRAP/repos/comb_spec_searcher/comb_spec_searcher/class_queue.py in __next__(self)
    216                     return wp
--> 217             self._populate_staging()
    218

~/Dropbox/Research/Active/2017-44-ATRAP/repos/comb_spec_searcher/comb_spec_searcher/class_queue.py in _populate_staging(self)
    168             if not self.curr_level:
--> 169                 self._change_level()
    170             self.staging.extend(self._iter_helper_curr())

~/Dropbox/Research/Active/2017-44-ATRAP/repos/comb_spec_searcher/comb_spec_searcher/class_queue.py in _change_level(self)
    181         if not self.curr_level:
--> 182             raise StopIteration
    183         self.queue_sizes.append(len(self.curr_level))

StopIteration:

During handling of the above exception, another exception occurred:

NoMoreClassesToExpandError                Traceback (most recent call last)
~/Dropbox/Research/Active/2017-44-ATRAP/repos/comb_spec_searcher/comb_spec_searcher/specification.py in _expand_verified_comb_classes(self, verification_packs)
    159                 try:
--> 160                     css.do_level()
    161                 except NoMoreClassesToExpandError:

~/Dropbox/Research/Active/2017-44-ATRAP/repos/comb_spec_searcher/comb_spec_searcher/comb_spec_searcher.py in do_level(self)
    405         found added to next."""
--> 406         for label, strategies, inferral in self.classqueue.do_level():
    407             comb_class = self.classdb.get_class(label)

~/Dropbox/Research/Active/2017-44-ATRAP/repos/comb_spec_searcher/comb_spec_searcher/class_queue.py in do_level(self)
    230                 if curr_level == self.levels_completed:
--> 231                     raise NoMoreClassesToExpandError
    232                 return

NoMoreClassesToExpandError:

During handling of the above exception, another exception occurred:

SpecificationNotFound                     Traceback (most recent call last)
<ipython-input-1-68aecd5fe0d9> in <module>
      6 pack = TileScopePack.insertion_row_and_col_placements(row_only=True).make_fusion(apply_first=True)
      7 css = TileScope(basis, pack)
----> 8 spec = css.auto_search()

~/Dropbox/Research/Active/2017-44-ATRAP/repos/comb_spec_searcher/comb_spec_searcher/comb_spec_searcher.py in auto_search(self, **kwargs)
    611                 smallest=kwargs.get("smallest", False),
    612                 expand_verified=kwargs.get("expand_verified", True),
--> 613                 minimization_time_limit=0.01 * (time.time() - auto_search_start),
    614             )
    615             if specification is not None:

~/Dropbox/Research/Active/2017-44-ATRAP/repos/comb_spec_searcher/comb_spec_searcher/utils.py in inner(css, *args, **kwargs)
     28         def inner(css: "CombinatorialSpecificationSearcher", *args, **kwargs):
     29             start = time.time()
---> 30             res = func(css, *args, **kwargs)
     31             css.func_times[self.explanation] += time.time() - start
     32             css.func_calls[self.explanation] += 1

~/Dropbox/Research/Active/2017-44-ATRAP/repos/comb_spec_searcher/comb_spec_searcher/comb_spec_searcher.py in get_specification(self, minimization_time_limit, smallest, expand_verified)
    674             [(self.classdb.get_class(label), rule) for label, rule in rules],
    675             comb_class_eqv_paths,
--> 676             expand_verified=expand_verified,
    677         )

~/Dropbox/Research/Active/2017-44-ATRAP/repos/comb_spec_searcher/comb_spec_searcher/specification.py in __init__(self, root, strategies, equivalence_paths, expand_verified)
     73         self.root = root
     74         self.rules_dict: Dict[CombinatorialClassType, AbstractRule] = {}
---> 75         self._populate_rules_dict(strategies, equivalence_paths, expand_verified)
     76         for rule in list(
     77             self.rules_dict.values()

~/Dropbox/Research/Active/2017-44-ATRAP/repos/comb_spec_searcher/comb_spec_searcher/specification.py in _populate_rules_dict(self, strategies, equivalence_paths, expand_verified)
    121                 raise ValueError("Non verification rule has no children.")
    122         self._add_equivalence_path_rules(equivalence_paths, equivalence_rules)
--> 123         self._expand_verified_comb_classes(verification_packs)
    124
    125     def _add_equivalence_path_rules(

~/Dropbox/Research/Active/2017-44-ATRAP/repos/comb_spec_searcher/comb_spec_searcher/specification.py in _expand_verified_comb_classes(self, verification_packs)
    162                     with DisableLogging(logging.INFO):
    163                         new_rules = css.ruledb.get_smallest_specification(
--> 164                             css.start_label
    165                         )
    166                     break

~/Dropbox/Research/Active/2017-44-ATRAP/repos/comb_spec_searcher/comb_spec_searcher/rule_db/base.py in get_smallest_specification(self, label, iterative)
    254
    255         if not self.equivdb[label] in rules_dict:
--> 256             raise SpecificationNotFound("No specification for label {}".format(label))
    257         tree = random_proof_tree(rules_dict, root=self.equivdb[label])
    258         minimum = 1

SpecificationNotFound: No specification for label 0
```

**Comment by christianbean** [comment]
When expanding the above tiling the first rule created is 
```
[D 200626 09:54:17 comb_spec_searcher:250] Adding combinatorial rule 0 -> (1, 2)
    factor with partition {(0, 0), (2, 0)} / {(1, 1)}
    +-+-+-+                                      +-+-+                                        +-+                            
    | |●| |                                   =  |\|\|                                     x  |●|                            
    +-+-+-+                                      +-+-+                                        +-+                            
    |\| |\|                                      \: Av+(01)                                   ●: point                       
    +-+-+-+                                      Requirement 0:                               Requirement 0:                 
    \: Av+(01)                                   0: (1, 0)                                    0: (0, 0)                      
    ●: point                                     Requirement 1:                               Assumption 0:                  
    Requirement 0:                               10: (0, 0), (0, 0)                           can count points in cell (0, 0)
    0: (1, 1)                                    Assumption 0:                                
    Requirement 1:                               can count points in cell (0, 0)              
    0: (2, 0)                                    Assumption 1:                                
    Requirement 2:                               can count points in cells (0, 0), (1, 0)     
    10: (0, 0), (0, 0)                           Assumption 2:                                
    Assumption 0:                                can count points in cell (1, 0)              
    can count points in cell (0, 0)                                                           
    Assumption 1:                                                                             
    can count points in cells (0, 0), (2, 0)                                                  
    Assumption 2:                                                                             
    can count points in cell (1, 1)                                                           
    Assumption 3:                                                                             
    can count points in cell (2, 0)  
```
Then the atom is verified, but 1 applies all of the verification strategies and fails. 
```
[D 200626 09:54:17 comb_spec_searcher:217] Expanding label 1 with verify atoms
[D 200626 09:54:17 comb_spec_searcher:217] Expanding label 1 with one by one verification
[D 200626 09:54:17 comb_spec_searcher:217] Expanding label 1 with monotone tree verification
[D 200626 09:54:17 comb_spec_searcher:217] Expanding label 1 with local verification
```
This should be an instance of monotone tree verification or local verification. The issue lies in LocalVerification - (note, to be monotone verified, you have to be local verified). We treat assumptions like we treat requirements, that is a requirement is local if all of the cells in all of the gridded perms in the requirement are in one cell. So that said, the assumption `can count points in cells (0, 0), (1, 0)` is not considered local. 

First I will add `InsertionEncodingVerificationStrategy` to these packs, which will verify and enumerate this class. Although, doing so brushes the real bug under the carpet. What should be the definition of local for a `TrackingAssumption`? How should the pack be updated to accommodate this choice? One solutions, and the likely the one we will go with, it is local if every gridded perm is local, and to accommodate we use the interleaving variation of the SplittingStrategy.
