### ISSUE TITLE
Sanity check failure

### ISSUE THREAD

**Issue by enadeau** [PermutaTriangle/Tilings#258]
I've encountered a new sanity check failure. Here's a snippet to reproduce.

```python
from tilings import GriddedPerm, Tiling
from permuta import Perm
from tilings.assumptions import TrackingAssumption
from tilings.strategies.requirement_insertion import \
    RequirementInsertionStrategy

strat = RequirementInsertionStrategy(
    gps=frozenset({GriddedPerm(Perm((0,)), ((0, 0),))}), ignore_parent=False
)

t = Tiling(
    obstructions=(
        GriddedPerm(Perm((0, 1, 2)), ((0, 0), (0, 0), (0, 0))),
        GriddedPerm(Perm((0, 1, 2)), ((2, 0), (2, 0), (2, 0))),
        GriddedPerm(Perm((0, 1, 2)), ((2, 0), (2, 0), (3, 0))),
        GriddedPerm(Perm((0, 1, 2)), ((2, 0), (3, 0), (3, 0))),
        GriddedPerm(Perm((0, 1, 2)), ((3, 0), (3, 0), (3, 0))),
        GriddedPerm(Perm((0, 2, 1)), ((0, 0), (0, 0), (1, 0))),
        GriddedPerm(Perm((0, 2, 1)), ((0, 0), (0, 0), (2, 0))),
        GriddedPerm(Perm((0, 2, 1)), ((0, 0), (0, 0), (3, 0))),
        GriddedPerm(Perm((1, 2, 0)), ((2, 0), (2, 0), (2, 0))),
        GriddedPerm(Perm((1, 2, 0)), ((2, 0), (2, 0), (3, 0))),
        GriddedPerm(Perm((1, 2, 0)), ((2, 0), (3, 0), (3, 0))),
        GriddedPerm(Perm((1, 2, 0)), ((3, 0), (3, 0), (3, 0))),
        GriddedPerm(Perm((0, 1, 2, 3)), ((0, 0), (0, 0), (1, 0), (1, 0))),
        GriddedPerm(Perm((0, 1, 2, 3)), ((0, 0), (0, 0), (1, 0), (2, 0))),
        GriddedPerm(Perm((0, 1, 2, 3)), ((0, 0), (0, 0), (1, 0), (3, 0))),
        GriddedPerm(Perm((0, 1, 2, 3)), ((0, 0), (0, 0), (2, 0), (2, 0))),
        GriddedPerm(Perm((0, 1, 2, 3)), ((0, 0), (0, 0), (2, 0), (3, 0))),
        GriddedPerm(Perm((0, 1, 2, 3)), ((0, 0), (0, 0), (3, 0), (3, 0))),
        GriddedPerm(Perm((0, 1, 2, 3)), ((0, 0), (1, 0), (1, 0), (1, 0))),
        GriddedPerm(Perm((0, 1, 2, 3)), ((0, 0), (1, 0), (1, 0), (2, 0))),
        GriddedPerm(Perm((0, 1, 2, 3)), ((0, 0), (1, 0), (1, 0), (3, 0))),
        GriddedPerm(Perm((0, 1, 2, 3)), ((0, 0), (1, 0), (2, 0), (2, 0))),
        GriddedPerm(Perm((0, 1, 2, 3)), ((0, 0), (1, 0), (2, 0), (3, 0))),
        GriddedPerm(Perm((0, 1, 2, 3)), ((0, 0), (1, 0), (3, 0), (3, 0))),
        GriddedPerm(Perm((0, 1, 2, 3)), ((1, 0), (1, 0), (1, 0), (1, 0))),
        GriddedPerm(Perm((0, 1, 2, 3)), ((1, 0), (1, 0), (1, 0), (2, 0))),
        GriddedPerm(Perm((0, 1, 2, 3)), ((1, 0), (1, 0), (1, 0), (3, 0))),
        GriddedPerm(Perm((0, 1, 2, 3)), ((1, 0), (1, 0), (2, 0), (2, 0))),
        GriddedPerm(Perm((0, 1, 2, 3)), ((1, 0), (1, 0), (2, 0), (3, 0))),
        GriddedPerm(Perm((0, 1, 2, 3)), ((1, 0), (1, 0), (3, 0), (3, 0))),
        GriddedPerm(Perm((0, 2, 3, 1)), ((0, 0), (1, 0), (1, 0), (1, 0))),
        GriddedPerm(Perm((0, 2, 3, 1)), ((0, 0), (1, 0), (1, 0), (2, 0))),
        GriddedPerm(Perm((0, 2, 3, 1)), ((0, 0), (1, 0), (1, 0), (3, 0))),
        GriddedPerm(Perm((0, 2, 3, 1)), ((0, 0), (1, 0), (2, 0), (2, 0))),
        GriddedPerm(Perm((0, 2, 3, 1)), ((0, 0), (1, 0), (2, 0), (3, 0))),
        GriddedPerm(Perm((0, 2, 3, 1)), ((0, 0), (1, 0), (3, 0), (3, 0))),
        GriddedPerm(Perm((0, 2, 3, 1)), ((1, 0), (1, 0), (1, 0), (1, 0))),
        GriddedPerm(Perm((0, 2, 3, 1)), ((1, 0), (1, 0), (1, 0), (2, 0))),
        GriddedPerm(Perm((0, 2, 3, 1)), ((1, 0), (1, 0), (1, 0), (3, 0))),
        GriddedPerm(Perm((0, 2, 3, 1)), ((1, 0), (1, 0), (2, 0), (2, 0))),
        GriddedPerm(Perm((0, 2, 3, 1)), ((1, 0), (1, 0), (2, 0), (3, 0))),
        GriddedPerm(Perm((0, 2, 3, 1)), ((1, 0), (1, 0), (3, 0), (3, 0))),
    ),
    requirements=((GriddedPerm(Perm((0,)), ((3, 0),)),),),
    assumptions=(TrackingAssumption((GriddedPerm(Perm((0,)), ((3, 0),)),)),),
)

rule = strat(t)
print(rule)
rule.sanity_check(5)
```

It gives
```
insert 0 in cell (0, 0)
+-+-+-+-+                                +-+-+-+                                  +-+-+-+-+                           
|1|2|3|4|                             =  |1|2|3|                               +  |1|2|3|4|                           
+-+-+-+-+                                +-+-+-+                                  +-+-+-+-+                           
1: Av(012)                               1: Av(0123, 0231)                        1: Av+(012)                         
2: Av(0123, 0231)                        2: Av(012, 120)                          2: Av(0123, 0231)                   
3: Av(012, 120)                          3: Av+(012, 120)                         3: Av(012, 120)                     
4: Av+(012, 120)                         Crossing obstructions:                   4: Av+(012, 120)                    
Crossing obstructions:                   012: (1, 0), (1, 0), (2, 0)              Crossing obstructions:              
012: (2, 0), (2, 0), (3, 0)              012: (1, 0), (2, 0), (2, 0)              012: (2, 0), (2, 0), (3, 0)         
012: (2, 0), (3, 0), (3, 0)              120: (1, 0), (1, 0), (2, 0)              012: (2, 0), (3, 0), (3, 0)         
021: (0, 0), (0, 0), (1, 0)              120: (1, 0), (2, 0), (2, 0)              021: (0, 0), (0, 0), (1, 0)         
021: (0, 0), (0, 0), (2, 0)              0123: (0, 0), (0, 0), (0, 0), (1, 0)     021: (0, 0), (0, 0), (2, 0)         
021: (0, 0), (0, 0), (3, 0)              0123: (0, 0), (0, 0), (0, 0), (2, 0)     021: (0, 0), (0, 0), (3, 0)         
120: (2, 0), (2, 0), (3, 0)              0123: (0, 0), (0, 0), (1, 0), (1, 0)     120: (2, 0), (2, 0), (3, 0)         
120: (2, 0), (3, 0), (3, 0)              0123: (0, 0), (0, 0), (1, 0), (2, 0)     120: (2, 0), (3, 0), (3, 0)         
0123: (0, 0), (0, 0), (1, 0), (1, 0)     0123: (0, 0), (0, 0), (2, 0), (2, 0)     0123: (0, 0), (0, 0), (1, 0), (1, 0)
0123: (0, 0), (0, 0), (1, 0), (2, 0)     0231: (0, 0), (0, 0), (0, 0), (1, 0)     0123: (0, 0), (0, 0), (1, 0), (2, 0)
0123: (0, 0), (0, 0), (1, 0), (3, 0)     0231: (0, 0), (0, 0), (0, 0), (2, 0)     0123: (0, 0), (0, 0), (1, 0), (3, 0)
0123: (0, 0), (0, 0), (2, 0), (2, 0)     0231: (0, 0), (0, 0), (1, 0), (1, 0)     0123: (0, 0), (0, 0), (2, 0), (2, 0)
0123: (0, 0), (0, 0), (2, 0), (3, 0)     0231: (0, 0), (0, 0), (1, 0), (2, 0)     0123: (0, 0), (0, 0), (2, 0), (3, 0)
0123: (0, 0), (0, 0), (3, 0), (3, 0)     0231: (0, 0), (0, 0), (2, 0), (2, 0)     0123: (0, 0), (0, 0), (3, 0), (3, 0)
0123: (0, 0), (1, 0), (1, 0), (1, 0)     Requirement 0:                           0123: (0, 0), (1, 0), (1, 0), (1, 0)
0123: (0, 0), (1, 0), (1, 0), (2, 0)     0: (2, 0)                                0123: (0, 0), (1, 0), (1, 0), (2, 0)
0123: (0, 0), (1, 0), (1, 0), (3, 0)     Assumption 0:                            0123: (0, 0), (1, 0), (1, 0), (3, 0)
0123: (0, 0), (1, 0), (2, 0), (2, 0)     can count points in cell (2, 0)          0123: (0, 0), (1, 0), (2, 0), (2, 0)
0123: (0, 0), (1, 0), (2, 0), (3, 0)                                              0123: (0, 0), (1, 0), (2, 0), (3, 0)
0123: (0, 0), (1, 0), (3, 0), (3, 0)                                              0123: (0, 0), (1, 0), (3, 0), (3, 0)
0123: (1, 0), (1, 0), (1, 0), (2, 0)                                              0123: (1, 0), (1, 0), (1, 0), (2, 0)
0123: (1, 0), (1, 0), (1, 0), (3, 0)                                              0123: (1, 0), (1, 0), (1, 0), (3, 0)
0123: (1, 0), (1, 0), (2, 0), (2, 0)                                              0123: (1, 0), (1, 0), (2, 0), (2, 0)
0123: (1, 0), (1, 0), (2, 0), (3, 0)                                              0123: (1, 0), (1, 0), (2, 0), (3, 0)
0123: (1, 0), (1, 0), (3, 0), (3, 0)                                              0123: (1, 0), (1, 0), (3, 0), (3, 0)
0231: (0, 0), (1, 0), (1, 0), (1, 0)                                              0231: (0, 0), (1, 0), (1, 0), (1, 0)
0231: (0, 0), (1, 0), (1, 0), (2, 0)                                              0231: (0, 0), (1, 0), (1, 0), (2, 0)
0231: (0, 0), (1, 0), (1, 0), (3, 0)                                              0231: (0, 0), (1, 0), (1, 0), (3, 0)
0231: (0, 0), (1, 0), (2, 0), (2, 0)                                              0231: (0, 0), (1, 0), (2, 0), (2, 0)
0231: (0, 0), (1, 0), (2, 0), (3, 0)                                              0231: (0, 0), (1, 0), (2, 0), (3, 0)
0231: (0, 0), (1, 0), (3, 0), (3, 0)                                              0231: (0, 0), (1, 0), (3, 0), (3, 0)
0231: (1, 0), (1, 0), (1, 0), (2, 0)                                              0231: (1, 0), (1, 0), (1, 0), (2, 0)
0231: (1, 0), (1, 0), (1, 0), (3, 0)                                              0231: (1, 0), (1, 0), (1, 0), (3, 0)
0231: (1, 0), (1, 0), (2, 0), (2, 0)                                              0231: (1, 0), (1, 0), (2, 0), (2, 0)
0231: (1, 0), (1, 0), (2, 0), (3, 0)                                              0231: (1, 0), (1, 0), (2, 0), (3, 0)
0231: (1, 0), (1, 0), (3, 0), (3, 0)                                              0231: (1, 0), (1, 0), (3, 0), (3, 0)
Requirement 0:                                                                    Requirement 0:                      
0: (3, 0)                                                                         0: (0, 0)                           
Assumption 0:                                                                     Requirement 1:                      
can count points in cell (3, 0)                                                   0: (3, 0)                           
                                                                                  Assumption 0:                       
                                                                                  can count points in cell (3, 0)     
Traceback (most recent call last):
  File "foo.py", line 62, in <module>
    rule.sanity_check(5)
  File "/home/enadeau/repos/comb_spec_searcher/comb_spec_searcher/strategies/rule.py", line 211, in sanity_check
    actual_count = brute_force_count(self.comb_class, n, **parameters)
  File "/home/enadeau/repos/comb_spec_searcher/comb_spec_searcher/strategies/rule.py", line 200, in brute_force_count
    ), f"{comb_class.extra_parameters, set(parameters)}"
AssertionError: (('k_0',), set())
```

**Comment by enadeau** [comment]
Never mind, this is not actually a bug. I needed to pass the extra parameters to the function.
